apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: observability
  labels:
    app: nginx-exporter
spec:
  type: ClusterIP
  selector:
    app: nginx-exporter
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
