apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: observability
data:
  default.conf: |
    server {
      listen 80;

      location / {
        return 200 "NGINX OK\n";
      }

      location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow all;
      }
    }
